version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api-bay

  nginx:
    container_name: nginx
    build: docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "81:80"
    depends_on:
      - db

  php:
    container_name: php
    build: docker/php
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db
